package com.example.flight_management_system.entity.enums;

public enum NotificationEventType {
    FLIGHT_DELAYED,
    FLIGHT_GATE_CHANGED,
    FLIGHT_CANCELLED,
    BOOKING_CANCELLED,
    BOOKING_REBOOKED,
    BOOKING_CONFIRMED,
    WAITLIST_PROMOTED,
    CHECK_IN_COMPLETED,
    SEAT_CHANGED,
    REFUND_REQUEST_SUBMITTED,
    REBOOK_REQUEST_SUBMITTED,
    PAYMENT_CAPTURED,
    REFUND_PROCESSED,
    CHARGEBACK_RECORDED
}
